const mongoose = require('mongoose');

const mappingSchema = mongoose.Schema({
	companyName: {
		type: String,
		required: true,
		unique: true,
	},
	companyID: {
		type: String,
		required: true,
		unique: true,
	},
	ID: {
		type: String,
	},
	CreateDate: {
		type: String,
	},
	UpdateDate: {
		type: String,
	},
	RecordStatus: {
		type: String,
	},
	Source: {
		type: String,
	},
	SourceId: {
		type: String,
	},
	BatchNumber: {
		type: String,
	},
	CompletedStages: {
		type: String,
	},
	EIN: {
		type: String,
	},
	Location: {
		type: String,
	},
	TaxId: {
		type: String,
	},
	FirstName: {
		type: String,
	},
	MiddleName: {
		type: String,
	},
	LastName: {
		type: String,
	},
	Suffix: {
		type: String,
	},
	EEPreTax: {
		type: String,
	},
	LoanRepayments: {
		type: String,
	},
	HoursWorkedYTD: {
		type: String,
	},
	Address1: {
		type: String,
	},
	Address2: {
		type: String,
	},
	City: {
		type: String,
	},
	State: {
		type: String,
	},
	PostalCode: {
		type: String,
	},
	BirthDate: {
		type: String,
	},
	HireDate: {
		type: String,
	},
	TerminationDate: {
		type: String,
	},
	RehireDate: {
		type: String,
	},
	Company: {
		type: String,
	},
	EmployeeStatus: {
		type: String,
	},
	EligibilityIndicator: {
		type: String,
	},
	CombinationRecordIdentifier: {
		type: String,
	},
	SanityCheckFlag: {
		type: String,
	},
	User_Defined_Float: {
		type: String,
	},
	Roth401kEE: {
		type: String,
	},
	stLoan: {
		type: String,
	},
	kLoan1: {
		type: String,
	},
	ndLoan: {
		type: String,
	},
	kLoan2: {
		type: String,
	},
	ERMatch: {
		type: String,
	},
	StatusChangeDate: {
		type: String,
	},
	StatusChangeReason: {
		type: String,
	},
	EmployeeEligibilityDate: {
		type: String,
	},
	EmployeeStartDate: {
		type: String,
	},
	ContractNumber: {
		type: String,
	},
	EmployerId: {
		type: String,
	},
	AscLocation: {
		type: String,
	},
	LastSanityCheckDate: {
		type: String,
	},
	PlanId: { type: String },
	EmployeeId: { type: String },
	LocationName: { type: String },
	TransType: { type: String },
	DeferralPercentage: { type: String },
	DeferralAmount: { type: String },
	AfterTaxPercentage: { type: String },
	AfterTaxAmount: { type: String },
	DeferralPercentEffectiveDate: { type: String },
	Division: { type: String },
	TransamericaRequestDate: { type: String },
	TransamericaEffectivePayrollChangeDate: { type: String },
	PriorPreTaxContribution: { type: String },
	PriorRothContribution: { type: String },
	NewPreTaxContribution: { type: String },
	NewRothContribution: { type: String },
	HardshipSuspension: { type: String },
	HardshipLiftDate: { type: String },
	PreTaxCatchUpPercent: { type: String },
	PreTaxCatchUpAmount: { type: String },
	RothCatchUpPercent: { type: String },
	RothCatchUpAmount: { type: String },
	TransamericaDateChanged: { type: String },
	MiddleInitial: { type: String },
	ErQacaMatch: { type: String },
	CompensationYTD: { type: String },
	Email: { type: String },
	PeriodHours: { type: String },
	PeriodGrossComp: { type: String },
	Loan1YTD: { type: String },
	Loan2YTD: { type: String },
	EEPreTaxYTD: { type: String },
	Roth401kEEYTD: { type: String },
	ERMatchYTD: { type: String },
	Roth401kERMatch: { type: String },
	Roth401kERMatchYTD: { type: String },
	DivisionName: { type: String },
	TermCode: { type: String },
	NeedsRepair: { type: String },
	RepairNotes: { type: String },
	Gender: { type: String },
	MaritalStatus: { type: String },
	PayFrequency: { type: String },
	CorporateOfficer: { type: String },
	IsUnion: { type: String },
	IsEligible: { type: String },
	IsHighlyCompensated: { type: String },
	CheckDate: { type: String },
	PayrollEndDate: { type: String },
	EEPreTaxPlan1: { type: String },
	EEPreTaxContrib1: { type: String },
	EEPreTaxContrib1Desc: { type: String },
	EEPreTaxContrib1Percent: { type: String },
	EEPreTaxContrib1Dollars: { type: String },
	EEPreTaxPlan2: { type: String },
	EEPreTaxContrib2: { type: String },
	EEPreTaxContrib2Desc: { type: String },
	EEPreTaxContrib2Percent: { type: String },
	EEPreTaxContrib2Dollars: { type: String },
	EEPreTaxPlan3: { type: String },
	EEPreTaxContrib3: { type: String },
	EEPreTaxContrib3Desc: { type: String },
	EEPreTaxContrib3Percent: { type: String },
	EEPreTaxContrib3Dollars: { type: String },
	PostTaxPlan1: { type: String },
	PostTaxContrib1: { type: String },
	PostTaxContrib1Desc: { type: String },
	PostTaxContrib1Percent: { type: String },
	PostTaxContrib1Dollars: { type: String },
	PostTaxPlan2: { type: String },
	PostTaxContrib2: { type: String },
	PostTaxContrib2Desc: { type: String },
	PostTaxContrib2Percent: { type: String },
	PostTaxContrib2Dollars: { type: String },
	PostTaxPlan3: { type: String },
	PostTaxContrib3: { type: String },
	PostTaxContrib3Desc: { type: String },
	PostTaxContrib3Percent: { type: String },
	PostTaxContrib3Dollars: { type: String },
	CatchUpPlan1: { type: String },
	CatchUpPlan1Contrib: { type: String },
	CatchUpPlan1ContribDesc: { type: String },
	CatchUpPlan2: { type: String },
	CatchUpPlan2Contrib: { type: String },
	CatchUpPlan2ContribDesc: { type: String },
	CatchUpPlan3: { type: String },
	CatchUpPlan3Contrib: { type: String },
	CatchUpPlan3ContribDesc: { type: String },
	ERMatch2: { type: String },
	ERMatch3: { type: String },
	ERCatchUpMatch: { type: String },
	ERCatchUpMatch2: { type: String },
	ERCatchUpMatch3: { type: String },
	thrdLoan: { type: String },
	kLoan3: { type: String },
	SafeHarborMatch: { type: String },
	Title: { type: String },
	EEPostTax: { type: String },
	EEMandatoryAfterTax: { type: String },
	ERNonMatch_ProfitSharing: { type: String },
	ERSafeHarborNonMatch_NonElective: { type: String },
	ERMoneyPurchase: { type: String },
	ERFullyVestedMoneyPurchase: { type: String },
	ERPrevailingWage: { type: String },
	QMAC: { type: String },
	QNEC: { type: String },
	ERQACA_NonElective: { type: String },
	ERQACAMatch: { type: String },
	ExcludedCompensationYTD: { type: String },
	IntlCityProvince: { type: String },
	IntlCountry: { type: String },
	Loan_Payoff: { type: String },
	IntlZipPostalCode: { type: String },
	JH_TransNum: { type: String },
	JH_PRDate: { type: String },
	JH_Calc_EEDef: { type: String },
	JH_Calc_SHMac: { type: String },
	JH_Calc_ERMat: { type: String },
	JH_Erps: { type: String },
	JH_EE403: { type: String },
	JH_EE457: { type: String },
	JH_EEIra: { type: String },
	JH_Calc_EERot: { type: String },
	JH_EERRT: { type: String },
	JH_EESEP: { type: String },
	JH_EESIR: { type: String },
	ERPS: { type: String },
	RKCalcComplete: { type: String },
	CalcSrc_401k$: { type: String },
	CalcSrc_401kPrct: { type: String },
	CalcSrc_Roth$: { type: String },
	CalcSrc_RothPrct: { type: String },
	CalcSrc_401k$Match: { type: String },
	CalcSrc_401kPrctMatch: { type: String },
	CalcSrc_Roth$Match: { type: String },
	CalcSrc_RothPrctMatch: { type: String },
	CalcSrc_401k$CU: { type: String },
	CalcSrc_401kPrctCU: { type: String },
	CalcSrc_Roth$CU: { type: String },
	CalcSrc_RothPrctCU: { type: String },
	CalcSrc_401k$CUMatch: { type: String },
	CalcSrc_401kPrctCUMatch: { type: String },
	CalcSrc_Roth$CUMatch: { type: String },
	CalcSrc_RothPrctCUMatch: { type: String },
	CalcSrc_PartialHours1: { type: String },
	CalcSrc_PartialHours2: { type: String },
	CalcSrc_PartialHours3: { type: String },
	CalcSrc_PartialHours4: { type: String },
	CalcSrc_PartialHours5: { type: String },
	CalcSrc_PartialHours6: { type: String },
	CalcSrc_PartialHours7: { type: String },
	CalcSrc_PartialHours8: { type: String },
	CalcSrc_PartialHours9: { type: String },
	CalcSrc_PartialHours10: { type: String },
	CalcSrc_PartialHours11: { type: String },
	CalcSrc_PartialHours12: { type: String },
	CalcSrc_PartialHours13: { type: String },
	CalcSrc_PartialHours14: { type: String },
	CalcSrc_PartialHours15: { type: String },
	CalcSrc_PartialHours16: { type: String },
	CalcSrc_PartialHours17: { type: String },
	CalcSrc_PartialHours18: { type: String },
	CalcSrc_PartialHours19: { type: String },
	CalcSrc_PartialHours20: { type: String },
	CalcSrc_LoanPmt1: { type: String },
	CalcSrc_LoanPmt2: { type: String },
	CalcSrc_LoanPmt3: { type: String },
	CalcSrc_LoanPmt4: { type: String },
	CalcSrc_LoanPmt5: { type: String },
	CalcSrc_LoanPmt6: { type: String },
	CalcSrc_LoanPmt7: { type: String },
	CalcSrc_LoanPmt8: { type: String },
	CalcSrc_LoanPmt9: { type: String },
	CalcSrc_LoanPmt10: { type: String },
	CalcSrc_LoanPmt11: { type: String },
	CalcSrc_LoanPmt12: { type: String },
	CalcSrc_LoanPmt13: { type: String },
	CalcSrc_LoanPmt14: { type: String },
	CalcSrc_LoanPmt15: { type: String },
	CalcSrc_LoanPmt16: { type: String },
	CalcSrc_LoanPmt17: { type: String },
	CalcSrc_ExclComp1: { type: String },
	CalcSrc_ExclComp2: { type: String },
	CalcSrc_ExclComp3: { type: String },
	CalcSrc_ExclComp4: { type: String },
	CalcSrc_ExclComp5: { type: String },
	CalcSrc_ExclComp6: { type: String },
	CalcSrc_ExclComp7: { type: String },
	CalcSrc_ExclComp8: { type: String },
	CalcSrc_ExclComp9: { type: String },
	CalcSrc_ExclComp10: { type: String },
	TotalLoans: { type: String },
	TotalPeriodHours: { type: String },
	TotalExcludedComp: { type: String },
	Roth401kERCUMatch: { type: String },
	TotalEEPreTax: { type: String },
	JH_Last_Suffix: { type: String },
	JH_NamePrefix: { type: String },
	JH_Country: { type: String },
	JH_EmployeeStatus: { type: String },
	JH_EligibilityIndicator: { type: String },
	JH_OptOutIndicator: { type: String },
	JH_BaseSalary: { type: String },
	JH_BfTxDefPct: { type: String },
	JH_DesigRothPct: { type: String },
	JH_BfTxFltDoDef: { type: String },
	JH_DesigRothAmt: { type: String },
	JH_Static_EmpStatus: { type: String },
	JH_Static_StatusDate: { type: String },
	JH_Static_IsEligible: { type: String },
	JH_Static_EligibleDate: { type: String },
	StaticSrc_CheckDate: { type: String },
	AlwaysBlank: { type: String },
	WorkEmail: { type: String },
	HomePhone: { type: String },
	EMP_Calc_Amt1: { type: String },
	EMP_Calc_Amt2: { type: String },
	EMP_Calc_Amt3: { type: String },
	EMP_Calc_Amt4: { type: String },
	EMP_Calc_Amt5: { type: String },
	EMP_Calc_Amt6: { type: String },
	EMP_Calc_Amt7: { type: String },
	EMP_Calc_Amt8: { type: String },
	EMP_Calc_Amt9: { type: String },
	EMP_Calc_Amt10: { type: String },
	EMP_SalaryAmountQualifier: { type: String },
	SalaryAmount: { type: String },
	EMP_Static_ContractNumber: { type: String },
	ERQACACUMatch: { type: String },
	DavisBacon: { type: String },
	TotalNonExcludedComp: { type: String },
	PayrollStartDate: { type: String },
	Voya_RecordType: { type: String },
	Voya_AnniversaryHours: { type: String },
	Voya_EligibilityCode: { type: String },
	Voya_ZipExtension: { type: String },
	Voya_LocationCode: { type: String },
	Voya_EmployerID: { type: String },
	Voya_IRSCode: { type: String },
	Voya_DepartmentCode: { type: String },
	WasADPRunProcessed: { type: String },
	ASC_Elig_Date1: { type: String },
	ASC_Elig_Date2: { type: String },
	ASC_Elig_Date3: { type: String },
	SafeHarborMatch_2: { type: String },
	SafeHarborMatch_3: { type: String },
	SafeHarborMatch_4: { type: String },
	SftpExportComplete: {type: String},
});

mappingSchema.methods.serialize = function() {
  return {
		companyName: this.companyName,
		companyID: this.companyID,
		ID: this.ID,
		CreateDate: this.CreateDate,
		UpdateDate: this.UpdateDate,
		RecordStatus: this.RecordStatus,
		Source: this.Source,
		SourceId: this.SourceId,
		BatchNumber: this.BatchNumber,
		CompletedStages: this.CompletedStages,
		EIN: this.EIN,
		Location: this.Location,
		TaxId: this.TaxId,
		FirstName: this.FirstName,
		MiddleName: this.MiddleName,
		LastName: this.LastName,
		Suffix: this.Suffix,
		EEPreTax: this.EEPreTax,
		LoanRepayments: this.LoanRepayments,
		HoursWorkedYTD: this.HoursWorkedYTD,
		Address1: this.Address1,
		Address2: this.Address2,
		City: this.City,
		State: this.State,
		PostalCode: this.PostalCode,
		BirthDate: this.BirthDate,
		HireDate: this.HireDate,
		TerminationDate: this.TerminationDate,
		RehireDate: this.RehireDate,
		Company: this.Company,
		EmployeeStatus: this.EmployeeStatus,
		EligibilityIndicator: this.EligibilityIndicator,
		CombinationRecordIdentifier: this.CombinationRecordIdentifier,
		SanityCheckFlag: this.SanityCheckFlag,
		User_Defined_Float: this.User_Defined_Float,
		Roth401kEE: this.Roth401kEE,
		stLoan: this.stLoan,
		kLoan1: this.kLoan1,
		ndLoan: this.ndLoan,
		kLoan2: this.kLoan2,
		ERMatch: this.ERMatch,
		StatusChangeDate: this.StatusChangeDate,
		StatusChangeReason: this.StatusChangeReason,
		EmployeeEligibilityDate: this.EmployeeEligibilityDate,
		EmployeeStartDate: this.EmployeeStartDate,
		ContractNumber: this.ContractNumber,
		EmployerId: this.EmployerId,
		AscLocation: this.AscLocation,
		LastSanityCheckDate: this.LastSanityCheckDate,
		PlanId: this.PlanId,
		EmployeeId: this.EmployeeId,
		LocationName: this.LocationName,
		TransType: this.TransType,
		DeferralPercentage: this.DeferralPercentage,
		DeferralAmount: this.DeferralAmount,
		AfterTaxPercentage: this.AfterTaxPercentage,
		AfterTaxAmount: this.AfterTaxAmount,
		DeferralPercentEffectiveDate: this.DeferralPercentEffectiveDate,
		Division: this.Division,
		TransamericaRequestDate: this.TransamericaRequestDate,
		TransamericaEffectivePayrollChangeDate: this
			.TransamericaEffectivePayrollChangeDate,
		PriorPreTaxContribution: this.PriorPreTaxContribution,
		PriorRothContribution: this.PriorRothContribution,
		NewPreTaxContribution: this.NewPreTaxContribution,
		NewRothContribution: this.NewRothContribution,
		HardshipSuspension: this.HardshipSuspension,
		HardshipLiftDate: this.HardshipLiftDate,
		PreTaxCatchUpPercent: this.PreTaxCatchUpPercent,
		PreTaxCatchUpAmount: this.PreTaxCatchUpAmount,
		RothCatchUpPercent: this.RothCatchUpPercent,
		RothCatchUpAmount: this.RothCatchUpAmount,
		TransamericaDateChanged: this.TransamericaDateChanged,
		MiddleInitial: this.MiddleInitial,
		ErQacaMatch: this.ErQacaMatch,
		CompensationYTD: this.CompensationYTD,
		Email: this.Email,
		PeriodHours: this.PeriodHours,
		PeriodGrossComp: this.PeriodGrossComp,
		Loan1YTD: this.Loan1YTD,
		Loan2YTD: this.Loan2YTD,
		EEPreTaxYTD: this.EEPreTaxYTD,
		Roth401kEEYTD: this.Roth401kEEYTD,
		ERMatchYTD: this.ERMatchYTD,
		Roth401kERMatch: this.Roth401kERMatch,
		Roth401kERMatchYTD: this.Roth401kERMatchYTD,
		DivisionName: this.DivisionName,
		TermCode: this.TermCode,
		NeedsRepair: this.NeedsRepair,
		RepairNotes: this.RepairNotes,
		Gender: this.Gender,
		MaritalStatus: this.MaritalStatus,
		PayFrequency: this.PayFrequency,
		CorporateOfficer: this.CorporateOfficer,
		IsUnion: this.IsUnion,
		IsEligible: this.IsEligible,
		IsHighlyCompensated: this.IsHighlyCompensated,
		CheckDate: this.CheckDate,
		PayrollEndDate: this.PayrollEndDate,
		EEPreTaxPlan1: this.EEPreTaxPlan1,
		EEPreTaxContrib1: this.EEPreTaxContrib1,
		EEPreTaxContrib1Desc: this.EEPreTaxContrib1Desc,
		EEPreTaxContrib1Percent: this.EEPreTaxContrib1Percent,
		EEPreTaxContrib1Dollars: this.EEPreTaxContrib1Dollars,
		EEPreTaxPlan2: this.EEPreTaxPlan2,
		EEPreTaxContrib2: this.EEPreTaxContrib2,
		EEPreTaxContrib2Desc: this.EEPreTaxContrib2Desc,
		EEPreTaxContrib2Percent: this.EEPreTaxContrib2Percent,
		EEPreTaxContrib2Dollars: this.EEPreTaxContrib2Dollars,
		EEPreTaxPlan3: this.EEPreTaxPlan3,
		EEPreTaxContrib3: this.EEPreTaxContrib3,
		EEPreTaxContrib3Desc: this.EEPreTaxContrib3Desc,
		EEPreTaxContrib3Percent: this.EEPreTaxContrib3Percent,
		EEPreTaxContrib3Dollars: this.EEPreTaxContrib3Dollars,
		PostTaxPlan1: this.PostTaxPlan1,
		PostTaxContrib1: this.PostTaxContrib1,
		PostTaxContrib1Desc: this.PostTaxContrib1Desc,
		PostTaxContrib1Percent: this.PostTaxContrib1Percent,
		PostTaxContrib1Dollars: this.PostTaxContrib1Dollars,
		PostTaxPlan2: this.PostTaxPlan2,
		PostTaxContrib2: this.PostTaxContrib2,
		PostTaxContrib2Desc: this.PostTaxContrib2Desc,
		PostTaxContrib2Percent: this.PostTaxContrib2Percent,
		PostTaxContrib2Dollars: this.PostTaxContrib2Dollars,
		PostTaxPlan3: this.PostTaxPlan3,
		PostTaxContrib3: this.PostTaxContrib3,
		PostTaxContrib3Desc: this.PostTaxContrib3Desc,
		PostTaxContrib3Percent: this.PostTaxContrib3Percent,
		PostTaxContrib3Dollars: this.PostTaxContrib3Dollars,
		CatchUpPlan1: this.CatchUpPlan1,
		CatchUpPlan1Contrib: this.CatchUpPlan1Contrib,
		CatchUpPlan1ContribDesc: this.CatchUpPlan1ContribDesc,
		CatchUpPlan2: this.CatchUpPlan2,
		CatchUpPlan2Contrib: this.CatchUpPlan2Contrib,
		CatchUpPlan2ContribDesc: this.CatchUpPlan2ContribDesc,
		CatchUpPlan3: this.CatchUpPlan3,
		CatchUpPlan3Contrib: this.CatchUpPlan3Contrib,
		CatchUpPlan3ContribDesc: this.CatchUpPlan3ContribDesc,
		ERMatch2: this.ERMatch2,
		ERMatch3: this.ERMatch3,
		ERCatchUpMatch: this.ERCatchUpMatch,
		ERCatchUpMatch2: this.ERCatchUpMatch2,
		ERCatchUpMatch3: this.ERCatchUpMatch3,
		thrdLoan: this.thrdLoan,
		kLoan3: this.kLoan3,
		SafeHarborMatch: this.SafeHarborMatch,
		Title: this.Title,
		EEPostTax: this.EEPostTax,
		EEMandatoryAfterTax: this.EEMandatoryAfterTax,
		ERNonMatch_ProfitSharing: this.ERNonMatch_ProfitSharing,
		ERSafeHarborNonMatch_NonElective: this.ERSafeHarborNonMatch_NonElective,
		ERMoneyPurchase: this.ERMoneyPurchase,
		ERFullyVestedMoneyPurchase: this.ERFullyVestedMoneyPurchase,
		ERPrevailingWage: this.ERPrevailingWage,
		QMAC: this.QMAC,
		QNEC: this.QNEC,
		ERQACA_NonElective: this.ERQACA_NonElective,
		ERQACAMatch: this.ERQACAMatch,
		ExcludedCompensationYTD: this.ExcludedCompensationYTD,
		IntlCityProvince: this.IntlCityProvince,
		IntlCountry: this.IntlCountry,
		Loan_Payoff: this.Loan_Payoff,
		IntlZipPostalCode: this.IntlZipPostalCode,
		JH_TransNum: this.JH_TransNum,
		JH_PRDate: this.JH_PRDate,
		JH_Calc_EEDef: this.JH_Calc_EEDef,
		JH_Calc_SHMac: this.JH_Calc_SHMac,
		JH_Calc_ERMat: this.JH_Calc_ERMat,
		JH_Erps: this.JH_Erps,
		JH_EE403: this.JH_EE403,
		JH_EE457: this.JH_EE457,
		JH_EEIra: this.JH_EEIra,
		JH_Calc_EERot: this.JH_Calc_EERot,
		JH_EERRT: this.JH_EERRT,
		JH_EESEP: this.JH_EESEP,
		JH_EESIR: this.JH_EESIR,
		ERPS: this.ERPS,
		RKCalcComplete: this.RKCalcComplete,
		CalcSrc_401k$: this.CalcSrc_401k$,
		CalcSrc_401kPrct: this.CalcSrc_401kPrct,
		CalcSrc_Roth$: this.CalcSrc_Roth$,
		CalcSrc_RothPrct: this.CalcSrc_RothPrct,
		CalcSrc_401k$Match: this.CalcSrc_401k$Match,
		CalcSrc_401kPrctMatch: this.CalcSrc_401kPrctMatch,
		CalcSrc_Roth$Match: this.CalcSrc_Roth$Match,
		CalcSrc_RothPrctMatch: this.CalcSrc_RothPrctMatch,
		CalcSrc_401k$CU: this.CalcSrc_401k$CU,
		CalcSrc_401kPrctCU: this.CalcSrc_401kPrctCU,
		CalcSrc_Roth$CU: this.CalcSrc_Roth$CU,
		CalcSrc_RothPrctCU: this.CalcSrc_RothPrctCU,
		CalcSrc_401k$CUMatch: this.CalcSrc_401k$CUMatch,
		CalcSrc_401kPrctCUMatch: this.CalcSrc_401kPrctCUMatch,
		CalcSrc_Roth$CUMatch: this.CalcSrc_Roth$CUMatch,
		CalcSrc_RothPrctCUMatch: this.CalcSrc_RothPrctCUMatch,
		CalcSrc_PartialHours1: this.CalcSrc_PartialHours1,
		CalcSrc_PartialHours2: this.CalcSrc_PartialHours2,
		CalcSrc_PartialHours3: this.CalcSrc_PartialHours3,
		CalcSrc_PartialHours4: this.CalcSrc_PartialHours4,
		CalcSrc_PartialHours5: this.CalcSrc_PartialHours5,
		CalcSrc_PartialHours6: this.CalcSrc_PartialHours6,
		CalcSrc_PartialHours7: this.CalcSrc_PartialHours7,
		CalcSrc_PartialHours8: this.CalcSrc_PartialHours8,
		CalcSrc_PartialHours9: this.CalcSrc_PartialHours9,
		CalcSrc_PartialHours10: this.CalcSrc_PartialHours10,
		CalcSrc_PartialHours11: this.CalcSrc_PartialHours11,
		CalcSrc_PartialHours12: this.CalcSrc_PartialHours12,
		CalcSrc_PartialHours13: this.CalcSrc_PartialHours13,
		CalcSrc_PartialHours14: this.CalcSrc_PartialHours14,
		CalcSrc_PartialHours15: this.CalcSrc_PartialHours15,
		CalcSrc_PartialHours16: this.CalcSrc_PartialHours16,
		CalcSrc_PartialHours17: this.CalcSrc_PartialHours17,
		CalcSrc_PartialHours18: this.CalcSrc_PartialHours18,
		CalcSrc_PartialHours19: this.CalcSrc_PartialHours19,
		CalcSrc_PartialHours20: this.CalcSrc_PartialHours20,
		CalcSrc_LoanPmt1: this.CalcSrc_LoanPmt1,
		CalcSrc_LoanPmt2: this.CalcSrc_LoanPmt2,
		CalcSrc_LoanPmt3: this.CalcSrc_LoanPmt3,
		CalcSrc_LoanPmt4: this.CalcSrc_LoanPmt4,
		CalcSrc_LoanPmt5: this.CalcSrc_LoanPmt5,
		CalcSrc_LoanPmt6: this.CalcSrc_LoanPmt6,
		CalcSrc_LoanPmt7: this.CalcSrc_LoanPmt7,
		CalcSrc_LoanPmt8: this.CalcSrc_LoanPmt8,
		CalcSrc_LoanPmt9: this.CalcSrc_LoanPmt9,
		CalcSrc_LoanPmt10: this.CalcSrc_LoanPmt10,
		CalcSrc_LoanPmt11: this.CalcSrc_LoanPmt11,
		CalcSrc_LoanPmt12: this.CalcSrc_LoanPmt12,
		CalcSrc_LoanPmt13: this.CalcSrc_LoanPmt13,
		CalcSrc_LoanPmt14: this.CalcSrc_LoanPmt14,
		CalcSrc_LoanPmt15: this.CalcSrc_LoanPmt15,
		CalcSrc_LoanPmt16: this.CalcSrc_LoanPmt16,
		CalcSrc_LoanPmt17: this.CalcSrc_LoanPmt17,
		CalcSrc_ExclComp1: this.CalcSrc_ExclComp1,
		CalcSrc_ExclComp2: this.CalcSrc_ExclComp2,
		CalcSrc_ExclComp3: this.CalcSrc_ExclComp3,
		CalcSrc_ExclComp4: this.CalcSrc_ExclComp4,
		CalcSrc_ExclComp5: this.CalcSrc_ExclComp5,
		CalcSrc_ExclComp6: this.CalcSrc_ExclComp6,
		CalcSrc_ExclComp7: this.CalcSrc_ExclComp7,
		CalcSrc_ExclComp8: this.CalcSrc_ExclComp8,
		CalcSrc_ExclComp9: this.CalcSrc_ExclComp9,
		CalcSrc_ExclComp10: this.CalcSrc_ExclComp10,
		TotalLoans: this.TotalLoans,
		TotalPeriodHours: this.TotalPeriodHours,
		TotalExcludedComp: this.TotalExcludedComp,
		Roth401kERCUMatch: this.Roth401kERCUMatch,
		TotalEEPreTax: this.TotalEEPreTax,
		JH_Last_Suffix: this.JH_Last_Suffix,
		JH_NamePrefix: this.JH_NamePrefix,
		JH_Country: this.JH_Country,
		JH_EmployeeStatus: this.JH_EmployeeStatus,
		JH_EligibilityIndicator: this.JH_EligibilityIndicator,
		JH_OptOutIndicator: this.JH_OptOutIndicator,
		JH_BaseSalary: this.JH_BaseSalary,
		JH_BfTxDefPct: this.JH_BfTxDefPct,
		JH_DesigRothPct: this.JH_DesigRothPct,
		JH_BfTxFltDoDef: this.JH_BfTxFltDoDef,
		JH_DesigRothAmt: this.JH_DesigRothAmt,
		JH_Static_EmpStatus: this.JH_Static_EmpStatus,
		JH_Static_StatusDate: this.JH_Static_StatusDate,
		JH_Static_IsEligible: this.JH_Static_IsEligible,
		JH_Static_EligibleDate: this.JH_Static_EligibleDate,
		StaticSrc_CheckDate: this.StaticSrc_CheckDate,
		AlwaysBlank: this.AlwaysBlank,
		WorkEmail: this.WorkEmail,
		HomePhone: this.HomePhone,
		EMP_Calc_Amt1: this.EMP_Calc_Amt1,
		EMP_Calc_Amt2: this.EMP_Calc_Amt2,
		EMP_Calc_Amt3: this.EMP_Calc_Amt3,
		EMP_Calc_Amt4: this.EMP_Calc_Amt4,
		EMP_Calc_Amt5: this.EMP_Calc_Amt5,
		EMP_Calc_Amt6: this.EMP_Calc_Amt6,
		EMP_Calc_Amt7: this.EMP_Calc_Amt7,
		EMP_Calc_Amt8: this.EMP_Calc_Amt8,
		EMP_Calc_Amt9: this.EMP_Calc_Amt9,
		EMP_Calc_Amt10: this.EMP_Calc_Amt10,
		EMP_SalaryAmountQualifier: this.EMP_SalaryAmountQualifier,
		SalaryAmount: this.SalaryAmount,
		EMP_Static_ContractNumber: this.EMP_Static_ContractNumber,
		ERQACACUMatch: this.ERQACACUMatch,
		DavisBacon: this.DavisBacon,
		TotalNonExcludedComp: this.TotalNonExcludedComp,
		PayrollStartDate: this.PayrollStartDate,
		Voya_RecordType: this.Voya_RecordType,
		Voya_AnniversaryHours: this.Voya_AnniversaryHours,
		Voya_EligibilityCode: this.Voya_EligibilityCode,
		Voya_ZipExtension: this.Voya_ZipExtension,
		Voya_LocationCode: this.Voya_LocationCode,
		Voya_EmployerID: this.Voya_EmployerID,
		Voya_IRSCode: this.Voya_IRSCode,
		Voya_DepartmentCode: this.Voya_DepartmentCode,
		WasADPRunProcessed: this.WasADPRunProcessed,
		ASC_Elig_Date1: this.ASC_Elig_Date1,
		ASC_Elig_Date2: this.ASC_Elig_Date2,
		ASC_Elig_Date3: this.ASC_Elig_Date3,
		SafeHarborMatch_2: this.SafeHarborMatch_2,
		SafeHarborMatch_3: this.SafeHarborMatch_3,
		SafeHarborMatch_4: this.SafeHarborMatch_4,
		SftpExportComplete: this.SftpExportComplete,
	};
};

const Mapping = mongoose.model('Mapping', mappingSchema);

module.exports = { Mapping };
