-- CREATE TABLE employees (
-- 	id INT AUTO_INCREMENT NOT NULL,
-- 	first_name VARCHAR(255) NOT NULL,
-- 	last_name VARCHAR(255) NOT NULL,
-- 	middle_name VARCHAR(255),
-- 	age INT NOT NULL,
-- 	current_status VARCHAR(255) NOT NULL DEFAULT 'employed',
-- 	PRIMARY KEY(id)
-- );

-- INSERT INTO employees(first_name, last_name, age) VALUES('Dora', 'Smith', 58);


CREATE TABLE header_mapping
(
    _id INT NOT NULL,
    companyName TINYTEXT,
    companyID INT(11),
    headers JSON,
    PRIMARY KEY (_id)
);


INSERT INTO header_mapping (companyName, companyID, headers)
VALUES
    (
        "Simplicity Consulting",
        48,
        '{
        "ID" : "ID",
    "CreateDate" : "CreateDate",
    "UpdateDate" : "UpdateDate",
    "RecordStatus" : "RecordStatus",
    "Source" : "Source",
    "SourceId" : "SourceId",
    "BatchNumber" : "BatchNumber",
    "CompletedStages" : "CompletedStages",
    "EIN" : "EIN",
    "Location" : "Location",
    "TaxId" : "SSN",
    "FirstName" : "First Name",
    "MiddleName" : "Middle Name",
    "LastName" : "Last Name",
    "Suffix" : "Name Suffix",
    "EEPreTax" : "EEPreTax",
    "LoanRepayments" : "LoanRepayments",
    "HoursWorkedYTD" : "Total Hours YTD",
    "Address1" : "Address 1",
    "Address2" : "Address 2",
    "City" : "City",
    "State" : "State/Province",
    "PostalCode" : "ZIP/Postal Code",
    "BirthDate" : "Birth Date",
    "HireDate" : "Hire Date",
    "TerminationDate" : "Termination Date",
    "RehireDate" : "Rehire Date",
    "Company" : "Company",
    "EmployeeStatus" : "EmployeeStatus",
    "EligibilityIndicator" : "EligibilityIndicator",
    "CombinationRecordIdentifier" : "CombinationRecordIdentifier",
    "SanityCheckFlag" : "SanityCheckFlag",
    "User_Defined_Float" : "User_Defined_Float",
    "Roth401kEE" : "Roth401kEE",
    "stLoan" : "1stLoan",
    "kLoan1" : "401kLoan1",
    "ndLoan" : "2ndLoan",
    "kLoan2" : "401kLoan2",
    "ERMatch" : "ERMatch",
    "StatusChangeDate" : "StatusChangeDate",
    "StatusChangeReason" : "StatusChangeReason",
    "EmployeeEligibilityDate" : "EmployeeEligibilityDate",
    "EmployeeStartDate" : "EmployeeStartDate",
    "ContractNumber" : "ContractNumber",
    "EmployerId" : "EmployerId",
    "AscLocation" : "AscLocation",
    "LastSanityCheckDate" : "LastSanityCheckDate",
    "PlanId" : "PlanId",
    "EmployeeId" : "EmployeeId",
    "LocationName" : "LocationName",
    "TransType" : "TransType",
    "DeferralPercentage" : "DeferralPercentage",
    "DeferralAmount" : "DeferralAmount",
    "AfterTaxPercentage" : "AfterTaxPercentage",
    "AfterTaxAmount" : "AfterTaxAmount",
    "DeferralPercentEffectiveDate" : "DeferralPercentEffectiveDate",
    "Division" : "Division",
    "TransamericaRequestDate" : "TransamericaRequestDate",
    "TransamericaEffectivePayrollChangeDate" : "TransamericaEffectivePayrollChangeDate",
    "PriorPreTaxContribution" : "PriorPreTaxContribution",
    "PriorRothContribution" : "PriorRothContribution",
    "NewPreTaxContribution" : "NewPreTaxContribution",
    "NewRothContribution" : "NewRothContribution",
    "HardshipSuspension" : "HardshipSuspension",
    "HardshipLiftDate" : "HardshipLiftDate",
    "PreTaxCatchUpPercent" : "PreTaxCatchUpPercent",
    "PreTaxCatchUpAmount" : "PreTaxCatchUpAmount",
    "RothCatchUpPercent" : "RothCatchUpPercent",
    "RothCatchUpAmount" : "RothCatchUpAmount",
    "TransamericaDateChanged" : "TransamericaDateChanged",
    "MiddleInitial" : "MiddleInitial",
    "ErQacaMatch" : "401kMatch Amount",
    "CompensationYTD" : "Gross Wages YTD",
    "Email" : "Work Email",
    "PeriodHours" : "PeriodHours",
    "PeriodGrossComp" : "PeriodGrossComp",
    "Loan1YTD" : "Loan1YTD",
    "Loan2YTD" : "Loan2YTD",
    "EEPreTaxYTD" : "EEPreTaxYTD",
    "Roth401kEEYTD" : "Roth401kEEYTD",
    "ERMatchYTD" : "ERMatchYTD",
    "Roth401kERMatch" : "Roth401kERMatch",
    "Roth401kERMatchYTD" : "Roth401kERMatchYTD",
    "DivisionName" : "DivisionName",
    "TermCode" : "TermCode",
    "NeedsRepair" : "NeedsRepair",
    "RepairNotes" : "RepairNotes",
    "Gender" : "Gender",
    "MaritalStatus" : "MaritalStatus",
    "PayFrequency" : "PayFrequency",
    "CorporateOfficer" : "CorporateOfficer",
    "IsUnion" : "IsUnion",
    "IsEligible" : "IsEligible",
    "IsHighlyCompensated" : "IsHighlyCompensated",
    "CheckDate" : "CheckDate",
    "PayrollEndDate" : "PayrollEndDate",
    "EEPreTaxPlan1" : "EEPreTaxPlan1",
    "EEPreTaxContrib1" : "EEPreTaxContrib1",
    "EEPreTaxContrib1Desc" : "EEPreTaxContrib1Desc",
    "EEPreTaxContrib1Percent" : "EEPreTaxContrib1Percent",
    "EEPreTaxContrib1Dollars" : "EEPreTaxContrib1Dollars",
    "EEPreTaxPlan2" : "EEPreTaxPlan2",
    "EEPreTaxContrib2" : "EEPreTaxContrib2",
    "EEPreTaxContrib2Desc" : "EEPreTaxContrib2Desc",
    "EEPreTaxContrib2Percent" : "EEPreTaxContrib2Percent",
    "EEPreTaxContrib2Dollars" : "EEPreTaxContrib2Dollars",
    "EEPreTaxPlan3" : "EEPreTaxPlan3",
    "EEPreTaxContrib3" : "EEPreTaxContrib3",
    "EEPreTaxContrib3Desc" : "EEPreTaxContrib3Desc",
    "EEPreTaxContrib3Percent" : "EEPreTaxContrib3Percent",
    "EEPreTaxContrib3Dollars" : "EEPreTaxContrib3Dollars",
    "PostTaxPlan1" : "PostTaxPlan1",
    "PostTaxContrib1" : "PostTaxContrib1",
    "PostTaxContrib1Desc" : "PostTaxContrib1Desc",
    "PostTaxContrib1Percent" : "PostTaxContrib1Percent",
    "PostTaxContrib1Dollars" : "PostTaxContrib1Dollars",
    "PostTaxPlan2" : "PostTaxPlan2",
    "PostTaxContrib2" : "PostTaxContrib2",
    "PostTaxContrib2Desc" : "PostTaxContrib2Desc",
    "PostTaxContrib2Percent" : "PostTaxContrib2Percent",
    "PostTaxContrib2Dollars" : "PostTaxContrib2Dollars",
    "PostTaxPlan3" : "PostTaxPlan3",
    "PostTaxContrib3" : "PostTaxContrib3",
    "PostTaxContrib3Desc" : "PostTaxContrib3Desc",
    "PostTaxContrib3Percent" : "PostTaxContrib3Percent",
    "PostTaxContrib3Dollars" : "PostTaxContrib3Dollars",
    "CatchUpPlan1" : "CatchUpPlan1",
    "CatchUpPlan1Contrib" : "CatchUpPlan1Contrib",
    "CatchUpPlan1ContribDesc" : "CatchUpPlan1ContribDesc",
    "CatchUpPlan2" : "CatchUpPlan2",
    "CatchUpPlan2Contrib" : "CatchUpPlan2Contrib",
    "CatchUpPlan2ContribDesc" : "CatchUpPlan2ContribDesc",
    "CatchUpPlan3" : "CatchUpPlan3",
    "CatchUpPlan3Contrib" : "CatchUpPlan3Contrib",
    "CatchUpPlan3ContribDesc" : "CatchUpPlan3ContribDesc",
    "ERMatch2" : "ERMatch2",
    "ERMatch3" : "ERMatch3",
    "ERCatchUpMatch" : "ERCatchUpMatch",
    "ERCatchUpMatch2" : "ERCatchUpMatch2",
    "ERCatchUpMatch3" : "ERCatchUpMatch3",
    "thrdLoan" : "3rdLoan",
    "kLoan3" : "401kLoan3",
    "SafeHarborMatch" : "SafeHarborMatch",
    "Title" : "Title",
    "EEPostTax" : "EEPostTax",
    "EEMandatoryAfterTax" : "EEMandatoryAfterTax",
    "ERNonMatch_ProfitSharing" : "ERNonMatch_ProfitSharing",
    "ERSafeHarborNonMatch_NonElective" : "ERSafeHarborNonMatch_NonElective",
    "ERMoneyPurchase" : "ERMoneyPurchase",
    "ERFullyVestedMoneyPurchase" : "ERFullyVestedMoneyPurchase",
    "ERPrevailingWage" : "ERPrevailingWage",
    "QMAC" : "QMAC",
    "QNEC" : "QNEC",
    "ERQACA_NonElective" : "ERQACA_NonElective",
    "ERQACAMatch" : "ErQacaMatch-Total",
    "ExcludedCompensationYTD" : "ExcludedCompensationYTD",
    "IntlCityProvince" : "IntlCityProvince",
    "IntlCountry" : "IntlCountry",
    "Loan_Payoff" : "Loan_Payoff",
    "IntlZipPostalCode" : "IntlZipPostalCode",
    "JH_TransNum" : "JH_TransNum",
    "JH_PRDate" : "JH_PRDate",
    "JH_Calc_EEDef" : "JH_Calc_EEDef",
    "JH_Calc_SHMac" : "JH_Calc_SHMac",
    "JH_Calc_ERMat" : "JH_Calc_ERMat",
    "JH_Erps" : "JH_Erps",
    "JH_EE403" : "JH_EE403",
    "JH_EE457" : "JH_EE457",
    "JH_EEIra" : "JH_EEIra",
    "JH_Calc_EERot" : "JH_Calc_EERot",
    "JH_EERRT" : "JH_EERRT",
    "JH_EESEP" : "JH_EESEP",
    "JH_EESIR" : "JH_EESIR",
    "ERPS" : "ERPS",
    "RKCalcComplete" : "RKCalcComplete",
    "CalcSrc_401k$" : "401k Amount",
    "CalcSrc_401kPrct" : "CalcSrc_401k%",
    "CalcSrc_Roth$" : "401kRoth Amount",
    "CalcSrc_RothPrct" : "CalcSrc_Roth%",
    "CalcSrc_401k$Match" : "CalcSrc_401k$Match",
    "CalcSrc_401kPrctMatch" : "CalcSrc_401k%Match",
    "CalcSrc_Roth$Match" : "CalcSrc_Roth$Match",
    "CalcSrc_RothPrctMatch" : "CalcSrc_Roth%Match",
    "CalcSrc_401k$CU" : "CalcSrc_401k$CU",
    "CalcSrc_401kPrctCU" : "CalcSrc_401k%CU",
    "CalcSrc_Roth$CU" : "CalcSrc_Roth$CU",
    "CalcSrc_RothPrctCU" : "CalcSrc_Roth%CU",
    "CalcSrc_401k$CUMatch" : "CalcSrc_401k$CUMatch",
    "CalcSrc_401kPrctCUMatch" : "CalcSrc_401k%CUMatch",
    "CalcSrc_Roth$CUMatch" : "CalcSrc_Roth$CUMatch",
    "CalcSrc_RothPrctCUMatch" : "CalcSrc_Roth%CUMatch",
    "CalcSrc_PartialHours1" : "CalcSrc_PartialHours1",
    "CalcSrc_PartialHours2" : "CalcSrc_PartialHours2",
    "CalcSrc_PartialHours3" : "CalcSrc_PartialHours3",
    "CalcSrc_PartialHours4" : "CalcSrc_PartialHours4",
    "CalcSrc_PartialHours5" : "CalcSrc_PartialHours5",
    "CalcSrc_PartialHours6" : "CalcSrc_PartialHours6",
    "CalcSrc_PartialHours7" : "CalcSrc_PartialHours7",
    "CalcSrc_PartialHours8" : "CalcSrc_PartialHours8",
    "CalcSrc_PartialHours9" : "CalcSrc_PartialHours9",
    "CalcSrc_PartialHours10" : "CalcSrc_PartialHours10",
    "CalcSrc_PartialHours11" : "CalcSrc_PartialHours11",
    "CalcSrc_PartialHours12" : "CalcSrc_PartialHours12",
    "CalcSrc_PartialHours13" : "CalcSrc_PartialHours13",
    "CalcSrc_PartialHours14" : "CalcSrc_PartialHours14",
    "CalcSrc_PartialHours15" : "CalcSrc_PartialHours15",
    "CalcSrc_PartialHours16" : "CalcSrc_PartialHours16",
    "CalcSrc_PartialHours17" : "CalcSrc_PartialHours17",
    "CalcSrc_PartialHours18" : "CalcSrc_PartialHours18",
    "CalcSrc_PartialHours19" : "CalcSrc_PartialHours19",
    "CalcSrc_PartialHours20" : "CalcSrc_PartialHours20",
    "CalcSrc_LoanPmt1" : "CalcSrc_LoanPmt1",
    "CalcSrc_LoanPmt2" : "CalcSrc_LoanPmt2",
    "CalcSrc_LoanPmt3" : "CalcSrc_LoanPmt3",
    "CalcSrc_LoanPmt4" : "CalcSrc_LoanPmt4",
    "CalcSrc_LoanPmt5" : "CalcSrc_LoanPmt5",
    "CalcSrc_LoanPmt6" : "CalcSrc_LoanPmt6",
    "CalcSrc_LoanPmt7" : "CalcSrc_LoanPmt7",
    "CalcSrc_LoanPmt8" : "CalcSrc_LoanPmt8",
    "CalcSrc_LoanPmt9" : "CalcSrc_LoanPmt9",
    "CalcSrc_LoanPmt10" : "CalcSrc_LoanPmt10",
    "CalcSrc_LoanPmt11" : "CalcSrc_LoanPmt11",
    "CalcSrc_LoanPmt12" : "CalcSrc_LoanPmt12",
    "CalcSrc_LoanPmt13" : "CalcSrc_LoanPmt13",
    "CalcSrc_LoanPmt14" : "CalcSrc_LoanPmt14",
    "CalcSrc_LoanPmt15" : "CalcSrc_LoanPmt15",
    "CalcSrc_LoanPmt16" : "CalcSrc_LoanPmt16",
    "CalcSrc_LoanPmt17" : "CalcSrc_LoanPmt17",
    "CalcSrc_ExclComp1" : "CalcSrc_ExclComp1",
    "CalcSrc_ExclComp2" : "CalcSrc_ExclComp2",
    "CalcSrc_ExclComp3" : "CalcSrc_ExclComp3",
    "CalcSrc_ExclComp4" : "CalcSrc_ExclComp4",
    "CalcSrc_ExclComp5" : "CalcSrc_ExclComp5",
    "CalcSrc_ExclComp6" : "CalcSrc_ExclComp6",
    "CalcSrc_ExclComp7" : "CalcSrc_ExclComp7",
    "CalcSrc_ExclComp8" : "CalcSrc_ExclComp8",
    "CalcSrc_ExclComp9" : "CalcSrc_ExclComp9",
    "CalcSrc_ExclComp10" : "CalcSrc_ExclComp10",
    "TotalLoans" : "TotalLoans",
    "TotalPeriodHours" : "TotalPeriodHours",
    "TotalExcludedComp" : "TotalExcludedComp",
    "Roth401kERCUMatch" : "Roth401kERCUMatch",
    "TotalEEPreTax" : "TotalEEPreTax",
    "JH_Last_Suffix" : "JH_Last_Suffix",
    "JH_NamePrefix" : "JH_NamePrefix",
    "JH_Country" : "JH_Country",
    "JH_EmployeeStatus" : "JH_EmployeeStatus",
    "JH_EligibilityIndicator" : "JH_EligibilityIndicator",
    "JH_OptOutIndicator" : "JH_OptOutIndicator",
    "JH_BaseSalary" : "JH_BaseSalary",
    "JH_BfTxDefPct" : "JH_BfTxDefPct",
    "JH_DesigRothPct" : "JH_DesigRothPct",
    "JH_BfTxFltDoDef" : "JH_BfTxFltDoDef",
    "JH_DesigRothAmt" : "JH_DesigRothAmt",
    "JH_Static_EmpStatus" : "JH_Static_EmpStatus",
    "JH_Static_StatusDate" : "JH_Static_StatusDate",
    "JH_Static_IsEligible" : "JH_Static_IsEligible",
    "JH_Static_EligibleDate" : "JH_Static_EligibleDate",
    "StaticSrc_CheckDate" : "StaticSrc_CheckDate",
    "AlwaysBlank" : "AlwaysBlank",
    "WorkEmail" : "Work Email",
    "HomePhone" : "HomePhone",
    "EMP_Calc_Amt1" : "EMP_Calc_Amt1",
    "EMP_Calc_Amt2" : "EMP_Calc_Amt2",
    "EMP_Calc_Amt3" : "EMP_Calc_Amt3",
    "EMP_Calc_Amt4" : "EMP_Calc_Amt4",
    "EMP_Calc_Amt5" : "EMP_Calc_Amt5",
    "EMP_Calc_Amt6" : "EMP_Calc_Amt6",
    "EMP_Calc_Amt7" : "EMP_Calc_Amt7",
    "EMP_Calc_Amt8" : "EMP_Calc_Amt8",
    "EMP_Calc_Amt9" : "EMP_Calc_Amt9",
    "EMP_Calc_Amt10" : "EMP_Calc_Amt10",
    "EMP_SalaryAmountQualifier" : "EMP_SalaryAmountQualifier",
    "SalaryAmount" : "SalaryAmount",
    "EMP_Static_ContractNumber" : "EMP_Static_ContractNumber",
    "ERQACACUMatch" : "ERQACACUMatch",
    "DavisBacon" : "DavisBacon",
    "TotalNonExcludedComp" : "TotalNonExcludedComp",
    "PayrollStartDate" : "PayrollStartDate",
    "Voya_RecordType" : "Voya_RecordType",
    "Voya_AnniversaryHours" : "Voya_AnniversaryHours",
    "Voya_EligibilityCode" : "Voya_EligibilityCode",
    "Voya_ZipExtension" : "Voya_ZipExtension",
    "Voya_LocationCode" : "Voya_LocationCode",
    "Voya_EmployerID" : "Voya_EmployerID",
    "Voya_IRSCode" : "Voya_IRSCode",
    "Voya_DepartmentCode" : "Voya_DepartmentCode",
    "WasADPRunProcessed" : "WasADPRunProcessed",
    "ASC_Elig_Date1" : "ASC_Elig_Date1",
    "ASC_Elig_Date2" : "ASC_Elig_Date2",
    "ASC_Elig_Date3" : "ASC_Elig_Date3",
    "SafeHarborMatch_2" : "SafeHarborMatch_2",
    "SafeHarborMatch_3" : "SafeHarborMatch_3",
    "SafeHarborMatch_4" : "SafeHarborMatch_4",
    "SftpExportComplete" : "SftpExportComplete"
    }'
);